[global]
disableWidgetStateDuplicationWarning = true

[theme]
primaryColor="#309842"
backgroundColor="#0a291b"
secondaryBackgroundColor="#073f32"
textColor="#b2dab2"
font="serif"

[logger]
level = "info"
messageFormat = "%(asctime)s %(levelname) -7s %(name)s: %(message)s"

[server]
runOnSave = true
headless = false