[global]
disableWidgetStateDuplicationWarning = true

[theme]
primaryColor="#7ad68a"
backgroundColor="#315c53"
secondaryBackgroundColor="#073521"
textColor="#e0e1dd"
font="serif"

[logger]
level = "info"
messageFormat = "%(asctime)s %(levelname) -7s %(name)s: %(message)s"

[server]
runOnSave = true
headless = false